/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NetNaviPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings/SettingsManager.ts
var DEFAULT_SETTINGS = {
  assetFolderPath: ".obsidian/plugins/netnavi-assistant/assets/",
  animationTiming: 5e3,
  videoAutoplay: true,
  volumeControl: 0.5,
  transitionFadeDuration: 300,
  uiPosition: { x: 20, y: 20 },
  enableAnimations: true,
  defaultAvatarSize: 150,
  uiMode: "docked",
  netnaviModeEnabled: true,
  textSpeed: "normal",
  enableGbaSound: true,
  stateMappings: {
    "onVaultModify": "taking_notes",
    "onWebSearchStart": "web_search",
    "onLocalRetrieval": "local_search",
    "onUsageLimit": "sleeping",
    "onResponseComplete": "idle"
  },
  aiConfig: {
    endpoint: "https://api.anthropic.com/v1/messages",
    apiKey: "",
    model: "claude-sonnet-4-5",
    systemPrompt: `You are NetNavi, an AI assistant living inside the user's Obsidian vault.
You have access to their notes, tasks, and memory systems.
When you perform actions, announce them clearly so the UI can react:
- "Searching the web for..."
- "Searching your vault for..."
- "Creating note at..."
When suggesting file changes, wrap them in a code block with <!-- path: folder/note.md --> on the first line.`
  }
};
var SettingsManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.current = { ...DEFAULT_SETTINGS };
  }
  async loadSettings() {
    var _a, _b;
    const loadedData = await this.plugin.loadData();
    this.current = {
      ...DEFAULT_SETTINGS,
      ...loadedData,
      aiConfig: { ...DEFAULT_SETTINGS.aiConfig, ...(_a = loadedData == null ? void 0 : loadedData.aiConfig) != null ? _a : {} },
      stateMappings: { ...DEFAULT_SETTINGS.stateMappings, ...(_b = loadedData == null ? void 0 : loadedData.stateMappings) != null ? _b : {} }
    };
  }
  async saveSettings() {
    await this.plugin.saveData(this.current);
  }
};

// src/states/StateManager.ts
var StateManager = class {
  constructor(initialState = "idle") {
    this.currentState = initialState;
    this.stateHistory = [initialState];
    this.listeners = [];
  }
  /**
   * Subscribe to state change events.
   */
  onChange(callback) {
    this.listeners.push(callback);
  }
  /**
   * Set the NetNavi to a new state.
   * @param newState The new emotion/state id (e.g., 'taking_notes', 'sleeping')
   */
  setState(newState) {
    if (this.currentState === newState)
      return;
    const oldState = this.currentState;
    this.stateHistory.push(newState);
    if (this.stateHistory.length > 50) {
      this.stateHistory.shift();
    }
    this.currentState = newState;
    for (const listener of this.listeners) {
      listener(this.currentState, oldState);
    }
  }
  getCurrentState() {
    return this.currentState;
  }
  getPreviousState() {
    if (this.stateHistory.length < 2)
      return null;
    return this.stateHistory[this.stateHistory.length - 2];
  }
  /**
   * Revert to the default idle sequence.
   */
  resetToIdle() {
    this.setState("idle");
  }
};

// src/ui/AvatarWidget.ts
var AvatarWidget = class {
  constructor(plugin, settingsManager) {
    this.plugin = plugin;
    this.settingsManager = settingsManager;
    this.isDragging = false;
    this.startX = 0;
    this.startY = 0;
    this.buildUI();
    this.attachDragEvents();
  }
  buildUI() {
    this.wrapper = document.createElement("div");
    this.wrapper.classList.add("netnavi-widget-wrapper");
    const pos = this.settingsManager.current.uiPosition;
    this.wrapper.style.left = `${Math.max(0, pos.x)}px`;
    this.wrapper.style.top = `${Math.max(0, pos.y)}px`;
    this.avatarContainer = document.createElement("div");
    this.avatarContainer.classList.add("netnavi-avatar-container");
    const size = this.settingsManager.current.defaultAvatarSize;
    this.avatarContainer.style.width = `${size}px`;
    this.avatarContainer.style.height = `${size}px`;
    this.chatContainer = document.createElement("div");
    this.chatContainer.classList.add("netnavi-chat-box");
    this.chatInput = document.createElement("textarea");
    this.chatInput.classList.add("netnavi-chat-input");
    this.chatInput.placeholder = "Message NetNavi...";
    this.chatInput.rows = 2;
    this.micButton = document.createElement("button");
    this.micButton.classList.add("netnavi-mic-button");
    this.micButton.innerHTML = "\u{1F3A4}";
    this.micButton.title = "Hold or click to talk";
    this.chatContainer.appendChild(this.chatInput);
    this.chatContainer.appendChild(this.micButton);
    this.wrapper.appendChild(this.avatarContainer);
    this.wrapper.appendChild(this.chatContainer);
    if (this.settingsManager.current.uiMode === "float") {
      document.body.appendChild(this.wrapper);
    }
  }
  attachTo(parent) {
    this.wrapper.classList.add("netnavi-docked");
    this.wrapper.style.left = "";
    this.wrapper.style.top = "";
    this.wrapper.style.position = "relative";
    parent.appendChild(this.wrapper);
  }
  detach() {
    this.wrapper.classList.remove("netnavi-docked");
    this.wrapper.style.position = "fixed";
    if (this.settingsManager.current.uiMode === "float") {
      const pos = this.settingsManager.current.uiPosition;
      this.wrapper.style.left = `${Math.max(0, pos.x)}px`;
      this.wrapper.style.top = `${Math.max(0, pos.y)}px`;
      document.body.appendChild(this.wrapper);
    } else {
      if (this.wrapper.parentElement) {
        this.wrapper.parentElement.removeChild(this.wrapper);
      }
    }
  }
  attachDragEvents() {
    this.wrapper.addEventListener("mousedown", (e) => {
      if (this.settingsManager.current.uiMode === "docked" || e.target === this.chatInput)
        return;
      this.isDragging = true;
      this.wrapper.classList.add("netnavi-dragging");
      const rect = this.wrapper.getBoundingClientRect();
      this.startX = e.clientX - rect.left;
      this.startY = e.clientY - rect.top;
    });
    document.addEventListener("mousemove", (e) => {
      if (!this.isDragging)
        return;
      e.preventDefault();
      const newX = e.clientX - this.startX;
      const newY = e.clientY - this.startY;
      this.wrapper.style.left = `${newX}px`;
      this.wrapper.style.top = `${newY}px`;
    });
    document.addEventListener("mouseup", async () => {
      if (this.isDragging) {
        this.isDragging = false;
        this.wrapper.classList.remove("netnavi-dragging");
        const rect = this.wrapper.getBoundingClientRect();
        this.settingsManager.current.uiPosition = { x: rect.left, y: rect.top };
        await this.settingsManager.saveSettings();
      }
    });
  }
  destroy() {
    if (this.wrapper && this.wrapper.parentElement) {
      this.wrapper.parentElement.removeChild(this.wrapper);
    }
  }
};

// src/ui/ResponsePanel.ts
var import_obsidian2 = require("obsidian");

// src/vault/VaultExecutor.ts
var import_obsidian = require("obsidian");
var VaultExecutor = class {
  constructor(app) {
    this.app = app;
  }
  async createNote(path4, content) {
    await this.ensureParentFolderExists(path4);
    const existingFile = this.app.vault.getAbstractFileByPath(path4);
    if (existingFile instanceof import_obsidian.TFile) {
      await this.app.vault.modify(existingFile, content);
      return existingFile;
    }
    return await this.app.vault.create(path4, content);
  }
  async modifyNote(path4, content) {
    const file = this.app.vault.getAbstractFileByPath(path4);
    if (file instanceof import_obsidian.TFile) {
      await this.app.vault.modify(file, content);
    } else {
      await this.createNote(path4, content);
    }
  }
  async readNote(path4) {
    const file = this.app.vault.getAbstractFileByPath(path4);
    if (file instanceof import_obsidian.TFile) {
      return await this.app.vault.read(file);
    }
    return null;
  }
  async createFolder(path4) {
    if (!await this.app.vault.adapter.exists(path4)) {
      await this.app.vault.createFolder(path4);
    }
  }
  /**
   * Parses an AI response for a file code block suggestion.
   * Expected format:
   * ```markdown
   * <!-- path: folder/note.md -->
   * Content here...
   * ```
   */
  static extractFileProposal(aiResponse) {
    const match = aiResponse.match(/```[\w]*\n<!-- path: (.+?) -->\n([\s\S]*?)```/);
    if (!match)
      return null;
    return {
      type: "create",
      path: match[1].trim(),
      content: match[2]
    };
  }
  async ensureParentFolderExists(filePath) {
    const parts = filePath.split("/");
    parts.pop();
    const folderPath = parts.join("/");
    if (folderPath && !await this.app.vault.adapter.exists(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
  }
};

// src/engines/TerminalEngine.ts
var TerminalEngine = class {
  constructor(settingsManager) {
    this.settingsManager = settingsManager;
    this.charDelayMs = 30;
    this.audioCtx = null;
    this.updateSpeed();
  }
  /**
   * Updates the character print delay according to user settings.
   */
  updateSpeed() {
    const speed = this.settingsManager.current.textSpeed;
    switch (speed) {
      case "slow":
        this.charDelayMs = 60;
        break;
      case "normal":
        this.charDelayMs = 30;
        break;
      case "fast":
        this.charDelayMs = 10;
        break;
      case "instant":
        this.charDelayMs = 0;
        break;
      default:
        this.charDelayMs = 30;
    }
  }
  /**
   * Streams text into an element character by character with retro beeps.
   */
  async streamText(text, element, onComplete) {
    element.classList.add("gba-printing");
    let consecutiveBeeps = 0;
    for (let i = 0; i < text.length; i++) {
      element.textContent += text[i];
      if (this.settingsManager.current.enableGbaSound && text[i].trim() !== "") {
        consecutiveBeeps++;
        if (consecutiveBeeps % 2 === 0) {
          this.playBeep();
        }
      } else {
        consecutiveBeeps = 0;
      }
      if (this.charDelayMs > 0) {
        await new Promise((resolve) => setTimeout(resolve, this.charDelayMs));
      }
    }
    element.classList.remove("gba-printing");
    if (onComplete) {
      onComplete();
    }
  }
  /**
   * Generates a synthesised high-pitch 8-bit retro sound beep using the browser's Web Audio API.
   */
  playBeep() {
    var _a;
    try {
      if (!this.audioCtx) {
        this.audioCtx = new (window.AudioContext || window.webkitAudioContext)();
      }
      if (this.audioCtx.state === "suspended") {
        this.audioCtx.resume();
      }
      const osc = this.audioCtx.createOscillator();
      const gain = this.audioCtx.createGain();
      osc.connect(gain);
      gain.connect(this.audioCtx.destination);
      osc.type = "triangle";
      osc.frequency.setValueAtTime(950, this.audioCtx.currentTime);
      const userVolume = (_a = this.settingsManager.current.volumeControl) != null ? _a : 0.5;
      const volumeScale = 0.015;
      gain.gain.setValueAtTime(userVolume * volumeScale, this.audioCtx.currentTime);
      osc.start();
      gain.gain.exponentialRampToValueAtTime(1e-5, this.audioCtx.currentTime + 0.035);
      osc.stop(this.audioCtx.currentTime + 0.04);
    } catch (e) {
      console.debug("[TerminalEngine] Audio Context blocked or unsupported:", e);
    }
  }
};

// src/ui/ResponsePanel.ts
var ResponsePanel = class {
  constructor(vaultExecutor, app, settingsManager) {
    this.vaultExecutor = vaultExecutor;
    this.app = app;
    this.settingsManager = settingsManager;
    this.currentStreamEl = null;
    this.currentStreamContent = "";
    this.markdownComponent = new import_obsidian2.Component();
    this.markdownComponent.load();
    this.terminalEngine = new TerminalEngine(this.settingsManager);
    this.buildUI();
  }
  buildUI() {
    this.containerEl = document.createElement("div");
    this.containerEl.id = "netnavi-response-panel";
    this.containerEl.classList.add("netnavi-response-panel");
    const header = this.containerEl.createDiv("netnavi-panel-header");
    header.createEl("span", { text: "\u2B21 NetNavi" });
    const clearBtn = header.createEl("button", { text: "\u2715 Clear" });
    clearBtn.onclick = () => this.clearHistory();
    this.historyEl = this.containerEl.createDiv("netnavi-panel-history");
    if (this.settingsManager.current.uiMode === "float") {
      document.body.appendChild(this.containerEl);
    }
  }
  attachTo(parent) {
    this.containerEl.classList.add("netnavi-docked");
    this.containerEl.style.position = "relative";
    this.containerEl.style.bottom = "";
    this.containerEl.style.right = "";
    this.containerEl.style.width = "100%";
    this.containerEl.style.maxHeight = "100%";
    parent.appendChild(this.containerEl);
  }
  detach() {
    this.containerEl.classList.remove("netnavi-docked");
    this.containerEl.style.position = "fixed";
    this.containerEl.style.bottom = "24px";
    this.containerEl.style.right = "24px";
    this.containerEl.style.width = "420px";
    this.containerEl.style.maxHeight = "60vh";
    if (this.settingsManager.current.uiMode === "float") {
      document.body.appendChild(this.containerEl);
    } else {
      if (this.containerEl.parentElement) {
        this.containerEl.parentElement.removeChild(this.containerEl);
      }
    }
  }
  /** Add a user message bubble to the history */
  addUserMessage(text) {
    const entry = this.historyEl.createDiv("netnavi-message netnavi-message-user");
    entry.createEl("p", { text });
    this.scrollToBottom();
  }
  /** Begin a new streaming assistant bubble */
  beginStream() {
    this.currentStreamContent = "";
    const entry = this.historyEl.createDiv("netnavi-message netnavi-message-assistant");
    const thinkingDots = entry.createDiv("netnavi-thinking");
    thinkingDots.innerHTML = "<span></span><span></span><span></span>";
    this.currentStreamEl = entry;
    this.scrollToBottom();
  }
  /** Append a token chunk to the current streaming bubble */
  async appendChunk(chunk) {
    if (!this.currentStreamEl)
      return;
    this.currentStreamContent += chunk;
    const cleanChunk = chunk.replace(/<!--action:.*?-->/gs, "");
    let textContainer = this.currentStreamEl.querySelector(".gba-text-container");
    if (!textContainer) {
      this.currentStreamEl.empty();
      textContainer = this.currentStreamEl.createDiv("gba-text-container");
      this.terminalEngine.updateSpeed();
    }
    await this.terminalEngine.streamText(cleanChunk, textContainer);
    this.scrollToBottom();
  }
  /** Finalize stream and check if there's a vault file proposal to display */
  async finalizeStream() {
    if (!this.currentStreamEl)
      return;
    const finalContent = this.currentStreamContent.replace(/<!--action:.*?-->/gs, "");
    this.currentStreamEl.empty();
    const mdContainer = this.currentStreamEl.createDiv("netnavi-markdown-body");
    await import_obsidian2.MarkdownRenderer.renderMarkdown(
      finalContent,
      mdContainer,
      "",
      this.markdownComponent
    );
    const proposal = VaultExecutor.extractFileProposal(this.currentStreamContent);
    if (proposal) {
      this.renderActionButtons(this.currentStreamEl, proposal);
    }
    this.currentStreamEl = null;
    this.currentStreamContent = "";
  }
  renderActionButtons(container, proposal) {
    const actions = container.createDiv("netnavi-action-buttons");
    actions.createEl("p", { text: `\u{1F4C4} Proposed: ${proposal.path}` }).style.opacity = "0.7";
    const acceptBtn = actions.createEl("button", { text: "\u2705 Accept" });
    acceptBtn.classList.add("netnavi-btn", "netnavi-btn-accept");
    acceptBtn.onclick = async () => {
      var _a;
      await this.vaultExecutor.createNote(proposal.path, (_a = proposal.content) != null ? _a : "");
      acceptBtn.textContent = "\u2705 Saved!";
      acceptBtn.disabled = true;
      rejectBtn.disabled = true;
    };
    const rejectBtn = actions.createEl("button", { text: "\u274C Reject" });
    rejectBtn.classList.add("netnavi-btn", "netnavi-btn-reject");
    rejectBtn.onclick = () => {
      actions.remove();
    };
    const previewBtn = actions.createEl("button", { text: "\u{1F441} Preview" });
    previewBtn.classList.add("netnavi-btn", "netnavi-btn-preview");
    previewBtn.onclick = async () => {
      var _a;
      const diffEl = actions.createDiv("netnavi-diff-preview");
      await import_obsidian2.MarkdownRenderer.renderMarkdown(
        "```\n" + ((_a = proposal.content) != null ? _a : "") + "\n```",
        diffEl,
        "",
        this.markdownComponent
      );
    };
  }
  clearHistory() {
    this.historyEl.empty();
    this.currentStreamEl = null;
  }
  scrollToBottom() {
    this.historyEl.scrollTop = this.historyEl.scrollHeight;
  }
  destroy() {
    this.markdownComponent.unload();
    if (this.containerEl.parentElement) {
      this.containerEl.parentElement.removeChild(this.containerEl);
    }
  }
};

// src/ui/ViewManager.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_NETNAVI = "netnavi-view";
var NetNaviView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_NETNAVI;
  }
  getDisplayText() {
    return "NetNavi Interface";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.classList.add("netnavi-docked-container");
    this.plugin.widget.attachTo(container);
    this.plugin.responsePanel.attachTo(container);
  }
  async onClose() {
    this.plugin.widget.detach();
    this.plugin.responsePanel.detach();
  }
};
var ViewManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  /**
   * Initializes and registers the NetNavi view in Obsidian.
   */
  registerViews() {
    this.plugin.registerView(
      VIEW_TYPE_NETNAVI,
      (leaf) => new NetNaviView(leaf, this.plugin)
    );
  }
  /**
   * Shows the NetNavi panel in the right sidebar or toggles its state.
   */
  async activateView() {
    const { workspace } = this.plugin.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_NETNAVI)[0] || null;
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_NETNAVI,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  /**
   * Closes/detaches the NetNavi views.
   */
  deactivateView() {
    this.plugin.app.workspace.detachLeavesOfType(VIEW_TYPE_NETNAVI);
  }
};

// src/avatar/AssetLoader.ts
var AssetLoader = class {
  constructor(app, baseAssetPath) {
    this.app = app;
    this.baseAssetPath = baseAssetPath;
    if (!this.baseAssetPath.endsWith("/")) {
      this.baseAssetPath += "/";
    }
  }
  /**
   * Scans the target folder for valid media files using the low-level
   * vault adapter (NOT vault.getFiles() which skips .obsidian/ directories).
   */
  async getAssetsForState(state) {
    const folderPath = `${this.baseAssetPath}${state}`;
    const validExtensions = ["png", "jpg", "jpeg", "gif", "webm", "mp4", "svg"];
    try {
      const listed = await this.app.vault.adapter.list(folderPath);
      return listed.files.filter((filePath) => {
        var _a, _b;
        const ext = (_b = (_a = filePath.split(".").pop()) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
        return validExtensions.includes(ext);
      }).map((filePath) => {
        var _a, _b;
        const ext = (_b = (_a = filePath.split(".").pop()) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
        const isVideo = ["webm", "mp4"].includes(ext);
        return {
          filePath,
          resolvedUri: this.app.vault.adapter.getResourcePath(filePath),
          type: isVideo ? "video" : "image"
        };
      });
    } catch (e) {
      console.warn(`[AssetLoader] Could not list assets at "${folderPath}":`, e);
      return [];
    }
  }
};

// src/avatar/MediaRenderer.ts
var MediaRenderer = class {
  constructor(container, fadeDurationMs = 300) {
    this.currentElement = null;
    this.container = container;
    this.fadeDurationMs = fadeDurationMs;
    this.container.classList.add("netnavi-media-container");
    this.container.style.position = "relative";
    this.container.style.overflow = "hidden";
  }
  /**
   * Renders a new asset and crossfades out the old one.
   */
  render(asset) {
    let newEl;
    if (asset.type === "video") {
      const video = document.createElement("video");
      video.src = asset.resolvedUri;
      video.autoplay = true;
      video.loop = true;
      video.muted = true;
      video.playsInline = true;
      newEl = video;
    } else {
      const img = document.createElement("img");
      img.src = asset.resolvedUri;
      newEl = img;
    }
    newEl.style.position = "absolute";
    newEl.style.top = "0";
    newEl.style.left = "0";
    newEl.style.width = "100%";
    newEl.style.height = "100%";
    newEl.style.objectFit = "contain";
    newEl.style.opacity = "0";
    newEl.style.transition = `opacity ${this.fadeDurationMs}ms ease-in-out`;
    this.container.appendChild(newEl);
    window.getComputedStyle(newEl).opacity;
    newEl.style.opacity = "1";
    if (this.currentElement) {
      const oldEl = this.currentElement;
      oldEl.style.opacity = "0";
      setTimeout(() => {
        if (oldEl.parentElement) {
          oldEl.parentElement.removeChild(oldEl);
        }
        if (oldEl instanceof HTMLVideoElement) {
          oldEl.pause();
          oldEl.removeAttribute("src");
          oldEl.load();
        }
      }, this.fadeDurationMs);
    }
    this.currentElement = newEl;
  }
  clear() {
    if (this.currentElement) {
      this.container.innerHTML = "";
      this.currentElement = null;
    }
  }
};

// src/avatar/IdleEngine.ts
var IdleEngine = class {
  constructor(assetLoader, renderer, rotationIntervalMs = 5e3) {
    this.assetLoader = assetLoader;
    this.renderer = renderer;
    this.rotationIntervalMs = rotationIntervalMs;
    this.timerId = null;
    this.idleAssets = [];
    this.lastAssetIndex = -1;
  }
  /**
   * Bootstraps the engine, loading the available assets and triggering the first rotation cycle.
   */
  async start() {
    this.idleAssets = await this.assetLoader.getAssetsForState("idle");
    if (this.idleAssets.length === 0) {
      console.warn("NetNavi: No idle assets found in /assets/idle/ folder.");
      return;
    }
    this.triggerRandomIdle();
    this.timerId = window.setInterval(() => {
      this.triggerRandomIdle();
    }, this.rotationIntervalMs);
  }
  /**
   * Halts the idle cycle safely.
   */
  stop() {
    if (this.timerId !== null) {
      window.clearInterval(this.timerId);
      this.timerId = null;
    }
  }
  /**
   * Selects a random asset, preventing back-to-back duplicate replays if there are multiple assets.
   */
  triggerRandomIdle() {
    if (this.idleAssets.length === 0)
      return;
    let randomIndex = Math.floor(Math.random() * this.idleAssets.length);
    if (this.idleAssets.length > 1 && randomIndex === this.lastAssetIndex) {
      randomIndex = (randomIndex + 1) % this.idleAssets.length;
    }
    this.lastAssetIndex = randomIndex;
    const asset = this.idleAssets[randomIndex];
    console.log(`[IdleEngine] Rotating idle animation to: ${asset.filePath}`);
    this.renderer.render(asset);
  }
};

// src/events/CooldownManager.ts
var CooldownManager = class {
  constructor(stateManager) {
    this.stateManager = stateManager;
    this.activeCooldown = null;
  }
  /**
   * Shifts the NetNavi state and automatically schedules a return to the 'idle' state.
   * Prevents overlapping cooldowns if multiple events fire in rapid succession.
   */
  triggerWithCooldown(state, durationMs = 3e3) {
    this.stateManager.setState(state);
    if (this.activeCooldown !== null) {
      window.clearTimeout(this.activeCooldown);
    }
    this.activeCooldown = window.setTimeout(() => {
      if (this.stateManager.getCurrentState() === state) {
        this.stateManager.resetToIdle();
      }
      this.activeCooldown = null;
    }, durationMs);
  }
};

// src/events/TriggerEvaluator.ts
var TriggerEvaluator = class {
  constructor(settingsManager, cooldownManager) {
    this.settingsManager = settingsManager;
    this.cooldownManager = cooldownManager;
  }
  /**
   * Resolves an incoming system event into an actionable NetNavi State.
   */
  handleEvent(eventName, payload) {
    const mappings = this.settingsManager.current.stateMappings;
    const targetState = mappings[eventName];
    if (targetState) {
      console.log(`[TriggerEvaluator] Event '${eventName}' detected. Transitioning to '${targetState}'.`);
      this.cooldownManager.triggerWithCooldown(targetState, 4e3);
    } else {
      console.debug(`[TriggerEvaluator] Unmapped event ignored: '${eventName}'`);
    }
  }
};

// src/events/EventBus.ts
var import_obsidian4 = require("obsidian");
var EventBus = class {
  constructor(plugin, evaluator) {
    this.plugin = plugin;
    this.evaluator = evaluator;
  }
  registerObsidianHooks() {
    const debouncedModify = (0, import_obsidian4.debounce)((file) => {
      this.sendEventToBackend("onVaultModify", {
        path: file.path,
        name: file.name,
        size: file.stat.size
      });
    }, 500);
    this.plugin.registerEvent(
      this.plugin.app.vault.on("modify", (file) => {
        if (!file.path.includes("netnavi-assistant") && !file.path.includes(".claudian")) {
          if (file instanceof import_obsidian4.TFile) {
            debouncedModify(file);
          }
          this.evaluator.handleEvent("onVaultModify", { file });
        } else {
          this.handleAssetFolderChange(file);
        }
      })
    );
    this.plugin.registerEvent(
      this.plugin.app.vault.on("create", (file) => {
        this.handleAssetFolderChange(file);
      })
    );
    this.plugin.registerEvent(
      this.plugin.app.workspace.on("active-leaf-change", () => {
        var _a, _b;
        const activeFile = this.plugin.app.workspace.getActiveFile();
        if (activeFile) {
          const cache = this.plugin.app.metadataCache.getFileCache(activeFile);
          const tags = ((_a = cache == null ? void 0 : cache.tags) == null ? void 0 : _a.map((t) => t.tag)) || [];
          const links = ((_b = cache == null ? void 0 : cache.links) == null ? void 0 : _b.map((l) => l.link)) || [];
          const frontmatter = (cache == null ? void 0 : cache.frontmatter) || {};
          this.sendEventToBackend("active-leaf-change", {
            path: activeFile.path,
            name: activeFile.name,
            tags,
            links,
            frontmatter
          });
        } else {
          this.sendEventToBackend("active-leaf-change", {
            path: null,
            name: null,
            tags: [],
            links: [],
            frontmatter: {}
          });
        }
      })
    );
    const debouncedCursorActivity = (0, import_obsidian4.debounce)(() => {
      const activeFile = this.plugin.app.workspace.getActiveFile();
      const view = this.plugin.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
      if (activeFile && view) {
        const editor = view.editor;
        const cursor = editor.getCursor();
        const cursorLine = cursor.line;
        const cache = this.plugin.app.metadataCache.getFileCache(activeFile);
        const headings = (cache == null ? void 0 : cache.headings) || [];
        const currentLevels = {};
        for (const h of headings) {
          if (h.position.start.line > cursorLine) {
            break;
          }
          currentLevels[h.level] = h.heading;
          for (let l = h.level + 1; l <= 6; l++) {
            delete currentLevels[l];
          }
        }
        const headingPath = Object.keys(currentLevels).map(Number).sort((a, b) => a - b).map((level) => currentLevels[level]);
        this.sendEventToBackend("cursor-activity", {
          path: activeFile.path,
          line: cursorLine,
          headingPath
        });
      }
    }, 500);
    this.plugin.registerDomEvent(document, "click", debouncedCursorActivity);
    this.plugin.registerDomEvent(document, "keyup", debouncedCursorActivity);
    this.plugin.addCommand({
      id: "trigger-usage-limit",
      name: "NetNavi: Trigger API Usage Limit (Sleep)",
      callback: () => {
        this.evaluator.handleEvent("onUsageLimit");
      }
    });
    this.plugin.addCommand({
      id: "trigger-local-search",
      name: "NetNavi: Trigger Local Vector Search",
      callback: () => {
        this.evaluator.handleEvent("onLocalRetrieval");
      }
    });
    this.plugin.addCommand({
      id: "trigger-web-search",
      name: "NetNavi: Trigger Web Search Event",
      callback: () => {
        this.evaluator.handleEvent("onWebSearchStart");
      }
    });
  }
  /**
   * Dispatches telemetry events to the core daemon.
   */
  async sendEventToBackend(eventType, payload) {
    try {
      await (0, import_obsidian4.requestUrl)({
        url: "http://127.0.0.1:8000/event",
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          event_type: eventType,
          payload
        })
      });
    } catch (e) {
      console.debug("[EventBus] Failed to dispatch event to ONCD:", e.message || e);
    }
  }
  /**
   * Hot-reloads the active aspect view if an asset in the configured asset folder changes.
   */
  handleAssetFolderChange(file) {
    const settings = this.plugin.settingsManager.current;
    const assetPath = settings.assetFolderPath;
    if (file.path.includes(assetPath) || file.path.includes("netnavi-assistant/assets")) {
      console.log(`[EventBus] Asset change detected at "${file.path}". Refreshing avatar state...`);
      const stateManager = this.plugin.stateManager;
      const currentState = stateManager.getCurrentState();
      stateManager.setState("idle");
      setTimeout(() => {
        stateManager.setState(currentState);
      }, 50);
    }
  }
};

// src/settings/EmotionEditorModal.ts
var import_obsidian5 = require("obsidian");
var EmotionEditorModal = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "NetNavi Assistant Settings" });
    containerEl.createEl("h3", { text: "\u{1F916} AI Connection" });
    new import_obsidian5.Setting(containerEl).setName("AI Endpoint").setDesc("URL of your AI API (Ollama: http://localhost:11434/api/chat \u2014 or any OpenAI-compatible endpoint).").addText((text) => {
      text.inputEl.style.width = "100%";
      text.setPlaceholder("http://localhost:11434/api/chat").setValue(this.plugin.settingsManager.current.aiConfig.endpoint).onChange(async (v) => {
        this.plugin.settingsManager.current.aiConfig.endpoint = v.trim();
        await this.plugin.settingsManager.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Model Name").setDesc("Anthropic: claude-opus-4-5 | claude-sonnet-4-5 | claude-3-5-sonnet-20241022 | claude-3-5-haiku-20241022. Ollama: llama3, mistral.").addText((text) => text.setPlaceholder("llama3").setValue(this.plugin.settingsManager.current.aiConfig.model).onChange(async (v) => {
      this.plugin.settingsManager.current.aiConfig.model = v.trim();
      await this.plugin.settingsManager.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("API Key").setDesc("Leave blank for local Ollama. Required for cloud APIs (OpenAI, Anthropic, etc).").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sk-...").setValue(this.plugin.settingsManager.current.aiConfig.apiKey).onChange(async (v) => {
        this.plugin.settingsManager.current.aiConfig.apiKey = v.trim();
        await this.plugin.settingsManager.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("System Prompt").setDesc("Personality and behavior instructions sent to the AI at the start of every session.").addTextArea((area) => {
      area.inputEl.rows = 6;
      area.inputEl.style.width = "100%";
      area.inputEl.style.fontFamily = "monospace";
      area.setValue(this.plugin.settingsManager.current.aiConfig.systemPrompt).onChange(async (v) => {
        this.plugin.settingsManager.current.aiConfig.systemPrompt = v;
        await this.plugin.settingsManager.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Test Connection").setDesc("Ping your endpoint to verify it is reachable.").addButton((btn) => btn.setButtonText("\u{1F517} Test").setCta().onClick(async () => {
      btn.setButtonText("Testing...");
      btn.setDisabled(true);
      const result = await this.plugin.aiClient.testConnection();
      btn.setButtonText(result.message);
      setTimeout(() => {
        btn.setButtonText("\u{1F517} Test");
        btn.setDisabled(false);
      }, 4e3);
    }));
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "\u{1FA9F} Widget Settings & View Mode" });
    new import_obsidian5.Setting(containerEl).setName("Enable NetNavi Mode").setDesc("Turn NetNavi widgets and dialogue system ON or OFF.").addToggle((toggle) => toggle.setValue(this.plugin.settingsManager.current.netnaviModeEnabled).onChange(async (value) => {
      this.plugin.settingsManager.current.netnaviModeEnabled = value;
      await this.plugin.settingsManager.saveSettings();
      if (value) {
        if (this.plugin.settingsManager.current.uiMode === "float") {
          document.body.appendChild(this.plugin.widget.wrapper);
          document.body.appendChild(this.plugin.responsePanel.containerEl);
        } else {
          this.plugin.viewManager.activateView();
        }
      } else {
        this.plugin.widget.detach();
        this.plugin.responsePanel.detach();
        this.plugin.viewManager.deactivateView();
      }
    }));
    new import_obsidian5.Setting(containerEl).setName("UI Display Mode").setDesc("Choose between a docked pane (recommended for PET theme) or a floating clippy-style overlay.").addDropdown((dropdown) => dropdown.addOption("docked", "Docked Pane").addOption("float", "Floating Overlay").setValue(this.plugin.settingsManager.current.uiMode).onChange(async (value) => {
      this.plugin.settingsManager.current.uiMode = value;
      await this.plugin.settingsManager.saveSettings();
      this.plugin.widget.detach();
      this.plugin.responsePanel.detach();
      this.plugin.viewManager.deactivateView();
      if (value === "float") {
        document.body.appendChild(this.plugin.widget.wrapper);
        document.body.appendChild(this.plugin.responsePanel.containerEl);
      } else {
        await this.plugin.viewManager.activateView();
      }
    }));
    new import_obsidian5.Setting(containerEl).setName("Asset Folder Path").setDesc("Directory where your NetNavi emotion assets are stored.").addText((text) => text.setPlaceholder(".obsidian/plugins/netnavi-assistant/assets/").setValue(this.plugin.settingsManager.current.assetFolderPath).onChange(async (value) => {
      this.plugin.settingsManager.current.assetFolderPath = value;
      await this.plugin.settingsManager.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Default Avatar Size").setDesc("Size of the floating NetNavi widget (in pixels).").addText((text) => text.setPlaceholder("150").setValue(String(this.plugin.settingsManager.current.defaultAvatarSize)).onChange(async (value) => {
      const size = parseInt(value, 10);
      if (!isNaN(size)) {
        this.plugin.settingsManager.current.defaultAvatarSize = size;
        await this.plugin.settingsManager.saveSettings();
        if (this.plugin.widget) {
          this.plugin.widget.avatarContainer.style.width = `${size}px`;
          this.plugin.widget.avatarContainer.style.height = `${size}px`;
        }
      }
    }));
    new import_obsidian5.Setting(containerEl).setName("Open Emotion Folder").setDesc("Open the physical directory containing all your GIF and MP4 assets in your OS file explorer.").addButton((btn) => btn.setButtonText("Open in File Explorer").onClick(async () => {
      try {
        const basePath = this.plugin.settingsManager.current.assetFolderPath;
        const absolutePath = this.plugin.app.vault.adapter.getBasePath() + "/" + basePath;
        const { shell } = require("electron");
        shell.openPath(absolutePath);
        new import_obsidian5.Notice("Opened NetNavi Assets folder!");
      } catch (e) {
        new import_obsidian5.Notice("Failed to open directory. Check your asset folder path.");
      }
    }));
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "\u{1F4C2} Emotion Asset Registry" });
    const registryInfo = containerEl.createEl("p", {
      text: "Drop GIFs, PNGs, or Videos into the zones below to upload them natively to Obsidian."
    });
    registryInfo.style.color = "var(--text-muted)";
    const registryDiv = containerEl.createDiv("netnavi-registry-grid");
    const emotions = ["idle", "sleeping", "happy", "sad", "taking_notes", "thinking_private", "thinking_public", "face_to_face", "error"];
    for (const emotion of emotions) {
      const card = registryDiv.createDiv("netnavi-emotion-card");
      card.style.border = "1px solid var(--background-modifier-border)";
      card.style.padding = "10px";
      card.style.margin = "10px 0";
      card.style.borderRadius = "8px";
      card.createEl("h4", { text: emotion.toUpperCase() });
      const dropZone = card.createDiv("netnavi-drop-zone");
      dropZone.style.border = "2px dashed var(--interactive-accent)";
      dropZone.style.padding = "20px";
      dropZone.style.textAlign = "center";
      dropZone.innerText = `Drop Image/Video for [${emotion}] here`;
      dropZone.addEventListener("dragover", (e) => {
        e.preventDefault();
        dropZone.style.backgroundColor = "var(--background-modifier-hover)";
      });
      dropZone.addEventListener("dragleave", (e) => {
        e.preventDefault();
        dropZone.style.backgroundColor = "transparent";
      });
      dropZone.addEventListener("drop", async (e) => {
        e.preventDefault();
        dropZone.style.backgroundColor = "transparent";
        if (e.dataTransfer && e.dataTransfer.files.length > 0) {
          const file = e.dataTransfer.files[0];
          const buffer = await file.arrayBuffer();
          const basePath = this.plugin.settingsManager.current.assetFolderPath;
          const folderPath = `${basePath}${emotion}`;
          const targetPath = `${folderPath}/${file.name}`;
          try {
            if (!await this.plugin.app.vault.adapter.exists(folderPath)) {
              await this.plugin.app.vault.adapter.mkdir(folderPath);
            }
            if (await this.plugin.app.vault.adapter.exists(targetPath)) {
              await this.plugin.app.vault.adapter.remove(targetPath);
            }
            await this.plugin.app.vault.adapter.writeBinary(targetPath, buffer);
            dropZone.innerText = `\u2705 Uploaded: ${file.name}`;
            new import_obsidian5.Notice(`Successfully added ${file.name} to ${emotion}!`);
          } catch (err) {
            console.error(err);
            dropZone.innerText = `\u274C Error saving file`;
          }
        }
      });
    }
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "\u26A1 Custom Trigger Builder" });
    const mappings = this.plugin.settingsManager.current.stateMappings;
    for (const [eventString, emotionTarget] of Object.entries(mappings)) {
      new import_obsidian5.Setting(containerEl).setName(`Event: ${eventString}`).setDesc(`Triggers Emotion: ${emotionTarget}`).addButton((button) => button.setButtonText("Remove").onClick(async () => {
        delete this.plugin.settingsManager.current.stateMappings[eventString];
        await this.plugin.settingsManager.saveSettings();
        this.display();
      }));
    }
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "\u{1F9EA} Live Testing Console" });
    new import_obsidian5.Setting(containerEl).setName("Test: Idle Sequence").setDesc("Force the NetNavi into its base idle cycle.").addButton((btn) => btn.setButtonText("Test").setCta().onClick(() => {
      this.plugin.stateManager.setState("idle");
    }));
  }
};

// src/ai/AntigravityClient.ts
var import_obsidian6 = require("obsidian");
var AntigravityClient = class {
  constructor(settingsManager) {
    this.settingsManager = settingsManager;
    this.isConnected = false;
  }
  get cfg() {
    return this.settingsManager.current.aiConfig;
  }
  detectProvider() {
    const url = this.cfg.endpoint.toLowerCase();
    if (url.includes("anthropic.com"))
      return "anthropic";
    if (url.includes("localhost:11434") || url.includes("127.0.0.1:11434"))
      return "ollama";
    return "openai";
  }
  /**
   * Sends a prompt and returns the full response via Obsidian's requestUrl.
   * Yields progressively-split chunks for live display in the ResponsePanel.
   */
  async *stream(userPrompt, history) {
    var _a;
    const provider = this.detectProvider();
    try {
      let responseText;
      if (provider === "anthropic") {
        responseText = await this.callAnthropic(userPrompt, history);
      } else {
        responseText = await this.callOpenAICompat(userPrompt, history);
      }
      this.isConnected = true;
      const words = responseText.split(" ");
      for (const word of words) {
        yield word + " ";
        await new Promise((r) => setTimeout(r, 8));
      }
    } catch (err) {
      this.isConnected = false;
      console.error("[AntigravityClient] Request failed:", err);
      yield '<!--action:{"action":"sleeping"}-->\n';
      yield `\u26A0\uFE0F **NetNavi cannot connect.** ${(_a = err == null ? void 0 : err.message) != null ? _a : "Unknown error"}

`;
      yield `Endpoint: \`${this.cfg.endpoint}\`
`;
      yield `Check: Settings \u2192 NetNavi Assistant \u2192 \u{1F916} AI Connection`;
    }
  }
  /**
   * Anthropic Messages API (Claude)
   * POST https://api.anthropic.com/v1/messages
   */
  async callAnthropic(userPrompt, history) {
    var _a, _b, _c;
    const messages = [
      ...history.toApiFormat(),
      { role: "user", content: userPrompt }
    ];
    const req = {
      url: this.cfg.endpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.cfg.apiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: this.cfg.model,
        max_tokens: 4096,
        system: this.cfg.systemPrompt,
        messages,
        stream: false
        // requestUrl does not support streaming; we simulate it
      })
    };
    const res = await (0, import_obsidian6.requestUrl)(req);
    if (res.status !== 200) {
      throw new Error(`Anthropic API error ${res.status}: ${res.text}`);
    }
    const parsed = res.json;
    const text = (_c = (_b = (_a = parsed == null ? void 0 : parsed.content) == null ? void 0 : _a[0]) == null ? void 0 : _b.text) != null ? _c : "";
    if (!text)
      throw new Error("Empty response from Anthropic API");
    return text;
  }
  /**
   * OpenAI-compatible format (Ollama, OpenAI, etc.)
   */
  async callOpenAICompat(userPrompt, history) {
    var _a, _b, _c, _d, _e, _f;
    const messages = [
      { role: "system", content: this.cfg.systemPrompt },
      ...history.toApiFormat(),
      { role: "user", content: userPrompt }
    ];
    const headers = {
      "Content-Type": "application/json"
    };
    if (this.cfg.apiKey) {
      headers["Authorization"] = `Bearer ${this.cfg.apiKey}`;
    }
    const req = {
      url: this.cfg.endpoint,
      method: "POST",
      headers,
      body: JSON.stringify({
        model: this.cfg.model,
        messages,
        stream: false
      })
    };
    const res = await (0, import_obsidian6.requestUrl)(req);
    if (res.status !== 200) {
      throw new Error(`API error ${res.status}: ${res.text}`);
    }
    const parsed = res.json;
    const text = (_f = (_e = (_c = (_b = (_a = parsed == null ? void 0 : parsed.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) != null ? _e : (_d = parsed == null ? void 0 : parsed.message) == null ? void 0 : _d.content) != null ? _f : "";
    if (!text)
      throw new Error("Empty response from API");
    return text;
  }
  /**
   * Tests connectivity. Provider-aware — uses the correct ping endpoint.
   */
  async testConnection() {
    var _a, _b, _c, _d, _e, _f;
    const provider = this.detectProvider();
    try {
      if (provider === "anthropic") {
        const req = {
          url: this.cfg.endpoint,
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": this.cfg.apiKey,
            "anthropic-version": "2023-06-01"
          },
          body: JSON.stringify({
            model: this.cfg.model,
            max_tokens: 5,
            messages: [{ role: "user", content: "Hi" }]
          }),
          throw: false
        };
        const res = await (0, import_obsidian6.requestUrl)(req);
        if (res.status === 200)
          return { ok: true, message: `\u2705 Claude connected (${this.cfg.model})` };
        let detail = "";
        try {
          const body = res.json;
          detail = (_c = (_b = (_a = body == null ? void 0 : body.error) == null ? void 0 : _a.message) != null ? _b : body == null ? void 0 : body.message) != null ? _c : JSON.stringify(body);
        } catch (e) {
          detail = (_e = (_d = res.text) == null ? void 0 : _d.slice(0, 120)) != null ? _e : `HTTP ${res.status}`;
        }
        if (res.status === 401)
          return { ok: false, message: `\u274C Invalid API key` };
        if (res.status === 400)
          return { ok: false, message: `\u274C Bad request: ${detail}` };
        if (res.status === 404)
          return { ok: false, message: `\u274C Model not found: "${this.cfg.model}"` };
        return { ok: false, message: `\u274C Error ${res.status}: ${detail}` };
      } else {
        const tagUrl = this.cfg.endpoint.replace("/api/chat", "/api/tags").replace("/v1/chat/completions", "/v1/models");
        const res = await (0, import_obsidian6.requestUrl)({ url: tagUrl, method: "GET", throw: false });
        if (res.status === 200)
          return { ok: true, message: `\u2705 Connected` };
        return { ok: false, message: `\u274C Error ${res.status}` };
      }
    } catch (e) {
      return { ok: false, message: `\u26A0\uFE0F Unreachable: ${(_f = e == null ? void 0 : e.message) != null ? _f : e}` };
    }
  }
  getConnectionStatus() {
    return this.isConnected;
  }
};

// src/ai/ConversationHistory.ts
var ConversationHistory = class {
  constructor() {
    this.messages = [];
    this.maxMessages = 60;
  }
  // 30 exchanges
  add(role, content) {
    this.messages.push({ role, content, timestamp: Date.now() });
    if (this.messages.length > this.maxMessages) {
      this.messages.splice(0, 2);
    }
  }
  getAll() {
    return [...this.messages];
  }
  /** Returns the history formatted for the API payload */
  toApiFormat() {
    return this.messages.map((m) => ({ role: m.role, content: m.content }));
  }
  clear() {
    this.messages = [];
  }
};

// src/ai/ActionParser.ts
var _ActionParser = class {
  /**
   * Tries structured JSON action first, falls back to keyword matching.
   * Returns null if no actionable state detected.
   */
  static parse(chunk) {
    const actionMatch = chunk.match(/<!--action:(.*?)-->/s);
    if (actionMatch) {
      try {
        const parsed = JSON.parse(actionMatch[1]);
        if (parsed.action)
          return parsed.action;
      } catch (e) {
      }
    }
    const lower = chunk.toLowerCase();
    for (const rule of _ActionParser.KEYWORD_RULES) {
      if (rule.keywords.some((k) => lower.includes(k))) {
        return rule.state;
      }
    }
    return null;
  }
};
var ActionParser = _ActionParser;
// Keyword rules: ordered from most specific to most generic
ActionParser.KEYWORD_RULES = [
  { keywords: ["searching the web", "browsing the internet", "web retrieval", "public api", "booklm"], state: "web_search" },
  { keywords: ["searching your vault", "looking through your notes", "pinecone", "local embedding", "vault retrieval", "reading vault"], state: "local_search" },
  { keywords: ["creating note", "modifying note", "writing to vault", "organizing vault", "creating folder"], state: "taking_notes" },
  { keywords: ["usage limit", "rate limit", "api unavailable", "connection interrupted", "offline"], state: "sleeping" },
  { keywords: ["let me think", "analyzing", "processing your request", "one moment"], state: "thinking" },
  { keywords: ["great job", "well done", "congratulations", "success"], state: "happy" },
  { keywords: ["error", "failed", "could not", "unfortunately"], state: "sad" }
];

// src/vault/StatusSync.ts
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var StatusSync = class {
  constructor(app, stateManager) {
    this.app = app;
    this.stateManager = stateManager;
    this.STATUS_PATH = ".claudian/status.json";
    this.pollTimer = null;
    this.lastKnownState = "idle";
    this.watcher = null;
    this.stateManager.onChange((newState) => {
      this.writeStatus(newState);
    });
  }
  /** Start watching status.json for external writes immediately */
  startPolling() {
    const adapter = this.app.vault.adapter;
    const basePath = adapter.basePath;
    if (!basePath) {
      console.warn("[StatusSync] basePath not found on adapter, using polling fallback");
      this.startPollingFallback();
      return;
    }
    const claudianDir = path.join(basePath, ".claudian");
    const statusFullPath = path.join(claudianDir, "status.json");
    try {
      if (!fs.existsSync(claudianDir)) {
        fs.mkdirSync(claudianDir, { recursive: true });
      }
    } catch (e) {
      console.warn("[StatusSync] Failed to create claudian directory:", e);
    }
    try {
      const targetToWatch = fs.existsSync(statusFullPath) ? statusFullPath : claudianDir;
      this.watcher = fs.watch(targetToWatch, (eventType, filename) => {
        if (eventType === "change" || filename === "status.json") {
          this.pollExternalChanges();
        }
      });
      console.log(`[StatusSync] Active fs.watch file watcher listening on: ${targetToWatch}`);
    } catch (e) {
      console.warn("[StatusSync] fs.watch failed to initialize. Falling back to polling:", e);
      this.startPollingFallback();
    }
  }
  startPollingFallback() {
    this.pollTimer = window.setInterval(() => this.pollExternalChanges(), 500);
    console.log("[StatusSync] Polling fallback started (500ms interval)");
  }
  stopPolling() {
    if (this.pollTimer !== null) {
      window.clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
    if (this.watcher !== null) {
      try {
        this.watcher.close();
      } catch (e) {
        console.warn("[StatusSync] Error closing watcher:", e);
      }
      this.watcher = null;
    }
  }
  async writeStatus(state, source, task) {
    const data = {
      current_state: state,
      source: source != null ? source : null,
      task: task != null ? task : null,
      timestamp: new Date().toISOString()
    };
    try {
      const rawContent = JSON.stringify(data, null, 2);
      await this.app.vault.adapter.write(this.STATUS_PATH, rawContent);
    } catch (e) {
      console.warn("[StatusSync] Could not write status.json:", e);
    }
  }
  async pollExternalChanges() {
    try {
      const raw = await this.app.vault.adapter.read(this.STATUS_PATH);
      const data = JSON.parse(raw);
      if (data.current_state && data.current_state !== this.lastKnownState) {
        this.lastKnownState = data.current_state;
        if (data.current_state !== this.stateManager.getCurrentState()) {
          console.log(`[StatusSync] Synchronizing external state change: ${data.current_state}`);
          this.stateManager.setState(data.current_state);
        }
      }
    } catch (e) {
    }
  }
};

// src/vault/VaultSearcher.ts
var VaultSearcher = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Search the vault for relevant notes based on terms in the query.
   * Ranks by occurrences in Title (weight 5) and Content (weight 1).
   */
  async search(query, limit = 3) {
    const cleanQuery = query.toLowerCase().trim();
    if (!cleanQuery)
      return [];
    const queryTerms = cleanQuery.split(/\s+/).filter((t) => t.length > 1);
    if (queryTerms.length === 0)
      return [];
    const files = this.app.vault.getMarkdownFiles();
    const results = [];
    for (const file of files) {
      let score = 0;
      const fileNameLower = file.name.toLowerCase();
      for (const term of queryTerms) {
        if (fileNameLower.includes(term)) {
          score += 5;
        }
      }
      try {
        const content = await this.app.vault.read(file);
        const contentLower = content.toLowerCase();
        for (const term of queryTerms) {
          const occurrences = contentLower.split(term).length - 1;
          score += occurrences;
        }
        if (score > 0) {
          let preview = "";
          const firstMatchIdx = contentLower.indexOf(queryTerms[0]);
          if (firstMatchIdx !== -1) {
            const start = Math.max(0, firstMatchIdx - 50);
            const end = Math.min(content.length, firstMatchIdx + 150);
            preview = content.slice(start, end).replace(/\n/g, " ") + "...";
          } else {
            preview = content.slice(0, 150).replace(/\n/g, " ") + "...";
          }
          results.push({
            file,
            score,
            preview: preview.trim()
          });
        }
      } catch (err) {
        continue;
      }
    }
    return results.sort((a, b) => b.score - a.score).slice(0, limit);
  }
  /**
   * Helper to bundle search results into a clean markdown format for context injection.
   */
  async formatContext(results) {
    if (results.length === 0) {
      return "No matching notes found in the vault.";
    }
    let context = "--- CONTEXT FROM USER VAULT ---\n";
    for (const res of results) {
      try {
        const content = await this.app.vault.read(res.file);
        context += `
Note Path: ${res.file.path}
`;
        context += `Content:
${content}
`;
        context += "-----------------------------\n";
      } catch (e) {
        continue;
      }
    }
    return context;
  }
};

// src/vault/LocalBridge.ts
var import_child_process = require("child_process");
var path2 = __toESM(require("path"));
var os = __toESM(require("os"));
var LocalBridge = class {
  constructor() {
    const home = os.homedir();
    this.pythonPath = path2.join(home, ".notebooklm-venv", "bin", "python3");
    this.scriptPath = path2.join(home, ".claude", "pinecone_memory.py");
  }
  /**
   * Executes semantic query to find memories matching a search prompt.
   */
  async query(text, topK = 3) {
    return new Promise((resolve) => {
      (0, import_child_process.execFile)(
        this.pythonPath,
        [this.scriptPath, "query", text, "--top-k", topK.toString()],
        (error, stdout, stderr) => {
          if (error) {
            console.error("[LocalBridge] Error querying Pinecone CLI:", error, stderr);
            resolve({ error: error.message || stderr });
            return;
          }
          try {
            const parsed = JSON.parse(stdout);
            resolve(parsed);
          } catch (e) {
            console.error("[LocalBridge] Failed to parse CLI output:", stdout);
            resolve({ error: `JSON Parse error: ${e.message}` });
          }
        }
      );
    });
  }
  /**
   * Stores new text inside your Pinecone index.
   */
  async store(text, tags = "") {
    return new Promise((resolve) => {
      const args = [this.scriptPath, "store", text];
      if (tags) {
        args.push("--tags", tags);
      }
      (0, import_child_process.execFile)(this.pythonPath, args, (error, stdout, stderr) => {
        if (error) {
          console.error("[LocalBridge] Error storing Pinecone CLI:", error, stderr);
          resolve({ status: "error", error: error.message || stderr });
          return;
        }
        try {
          const parsed = JSON.parse(stdout);
          resolve(parsed);
        } catch (e) {
          console.error("[LocalBridge] Failed to parse store output:", stdout);
          resolve({ status: "error", error: `JSON Parse error: ${e.message}` });
        }
      });
    });
  }
  /**
   * Checks if the virtualenv and script exist on the filesystem.
   */
  async checkSetup() {
    const fs2 = require("fs");
    try {
      return fs2.existsSync(this.pythonPath) && fs2.existsSync(this.scriptPath);
    } catch (e) {
      return false;
    }
  }
};

// src/engines/VoiceEngine.ts
var VoiceEngine = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.audioContext = null;
    this.stream = null;
    this.processor = null;
    this.leftChannel = [];
    this.isRecording = false;
  }
  async startRecording(micButton) {
    if (this.isRecording)
      return;
    this.isRecording = true;
    this.leftChannel = [];
    micButton.classList.add("netnavi-recording");
    micButton.innerHTML = "\u{1F6D1}";
    try {
      this.stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      this.audioContext = new (window.AudioContext || window.webkitAudioContext)({
        sampleRate: 16e3
      });
      const source = this.audioContext.createMediaStreamSource(this.stream);
      this.processor = this.audioContext.createScriptProcessor(4096, 1, 1);
      this.processor.onaudioprocess = (e) => {
        const inputData = e.inputBuffer.getChannelData(0);
        this.leftChannel.push(new Float32Array(inputData));
      };
      source.connect(this.processor);
      this.processor.connect(this.audioContext.destination);
    } catch (err) {
      console.error("[VoiceEngine] Failed to initialize microphone capture:", err);
      this.cleanup(micButton);
    }
  }
  async stopRecording(micButton) {
    if (!this.isRecording)
      return null;
    this.isRecording = false;
    micButton.classList.remove("netnavi-recording");
    micButton.innerHTML = "\u{1F3A4}";
    if (this.processor) {
      this.processor.disconnect();
      this.processor = null;
    }
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
      this.stream = null;
    }
    if (this.audioContext) {
      this.audioContext.close();
      this.audioContext = null;
    }
    if (this.leftChannel.length === 0)
      return null;
    const totalLength = this.leftChannel.reduce((acc, val) => acc + val.length, 0);
    const result = new Float32Array(totalLength);
    let offset = 0;
    for (const chunk of this.leftChannel) {
      result.set(chunk, offset);
      offset += chunk.length;
    }
    const wavBuffer = this.encodeWAV(result, 16e3);
    return wavBuffer;
  }
  cleanup(micButton) {
    this.isRecording = false;
    micButton.classList.remove("netnavi-recording");
    micButton.innerHTML = "\u{1F3A4}";
    if (this.processor) {
      this.processor.disconnect();
      this.processor = null;
    }
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
      this.stream = null;
    }
    if (this.audioContext) {
      this.audioContext.close();
      this.audioContext = null;
    }
  }
  encodeWAV(samples, sampleRate) {
    const buffer = new ArrayBuffer(44 + samples.length * 2);
    const view = new DataView(buffer);
    this.writeString(view, 0, "RIFF");
    view.setUint32(4, 36 + samples.length * 2, true);
    this.writeString(view, 8, "WAVE");
    this.writeString(view, 12, "fmt ");
    view.setUint32(16, 16, true);
    view.setUint16(20, 1, true);
    view.setUint16(22, 1, true);
    view.setUint32(24, sampleRate, true);
    view.setUint32(28, sampleRate * 2, true);
    view.setUint16(32, 2, true);
    view.setUint16(34, 16, true);
    this.writeString(view, 36, "data");
    view.setUint32(40, samples.length * 2, true);
    let offset = 44;
    for (let i = 0; i < samples.length; i++, offset += 2) {
      const s = Math.max(-1, Math.min(1, samples[i]));
      view.setInt16(offset, s < 0 ? s * 32768 : s * 32767, true);
    }
    return buffer;
  }
  writeString(view, offset, str) {
    for (let i = 0; i < str.length; i++) {
      view.setUint8(offset + i, str.charCodeAt(i));
    }
  }
  /**
   * TTS: Attempts backend cache retrieval, falling back to Web Speech API.
   */
  async speak(text) {
    try {
      const url = `http://127.0.0.1:8000/voice/tts?text=${encodeURIComponent(text)}`;
      const res = await fetch(url);
      if (res.ok && res.status === 200) {
        const arrayBuffer = await res.arrayBuffer();
        if (arrayBuffer.byteLength > 0) {
          const ctx = new (window.AudioContext || window.webkitAudioContext)();
          const audioBuffer = await ctx.decodeAudioData(arrayBuffer);
          const source = ctx.createBufferSource();
          source.buffer = audioBuffer;
          source.connect(ctx.destination);
          source.start(0);
          console.log("[VoiceEngine] TTS audio segment played from backend cache.");
          return;
        }
      }
    } catch (err) {
      console.debug("[VoiceEngine] Backend TTS unavailable or empty, falling back to browser synthesis.");
    }
    this.speakWebSpeech(text);
  }
  speakWebSpeech(text) {
    if ("speechSynthesis" in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 1;
      utterance.pitch = 1;
      window.speechSynthesis.speak(utterance);
      console.log("[VoiceEngine] TTS audio synthesized via Web Speech API.");
    } else {
      console.warn("[VoiceEngine] Web Speech API is not supported in this client environment.");
    }
  }
};

// src/vault/CommsBridge.ts
var import_child_process2 = require("child_process");
var CommsBridge = class {
  constructor(pythonPath, scriptPath) {
    this.pythonPath = pythonPath;
    this.scriptPath = scriptPath;
    this.process = null;
    this.onMessage = () => {
    };
    this.isRunning = false;
  }
  start(onMessage) {
    var _a;
    if (this.isRunning)
      return;
    this.onMessage = onMessage;
    console.log(`[CommsBridge] Starting background process: ${this.pythonPath} ${this.scriptPath}`);
    const env = { ...process.env, NETNAVI_KEYS_FILE: "netnavi_keys.json" };
    this.process = (0, import_child_process2.spawn)(this.pythonPath, [this.scriptPath], { env });
    this.isRunning = true;
    (_a = this.process.stdout) == null ? void 0 : _a.on("data", (data) => {
      const lines = data.toString().split("\n");
      for (const line of lines) {
        this.parseLine(line);
      }
    });
    this.process.on("close", (code) => {
      console.log(`[CommsBridge] Python process exited with code ${code}`);
      this.isRunning = false;
      this.process = null;
      this.onMessage("system", "\u{1F534} P.E.T. Connection Server Offline.");
    });
  }
  parseLine(line) {
    const cleanLine = line.replace(/\x1B\[[0-9;]*[a-zA-Z]/g, "").trim();
    if (!cleanLine)
      return;
    if (cleanLine.includes("MegaMan.EXE:") || cleanLine.includes("ProtoMan.EXE:") || cleanLine.includes("Peer:") || cleanLine.includes("Peer (Nostr):")) {
      const parts = cleanLine.split(":");
      const sender = parts[0].trim();
      const content = parts.slice(1).join(":").trim();
      const cleanContent = content.startsWith('"') && content.endsWith('"') ? content.slice(1, -1) : content;
      this.onMessage("peer", `**${sender}**: "${cleanContent}"`);
    } else if (cleanLine.includes("\u2714 HANDSHAKE GRANTED!")) {
      this.onMessage("system", "\u{1F49A} **EML Handshake Successful!** Soul Unison established.");
    } else if (cleanLine.includes("\u2714 Nostr Handshake SUCCESS!")) {
      this.onMessage("system", "\u{1F49A} **EML Nostr Handshake Successful!** Soul Unison established.");
    } else if (cleanLine.includes("\u2718 HANDSHAKE DENIED!") || cleanLine.includes("\u2718 Nostr Handshake FAILED!")) {
      this.onMessage("system", "\u{1F494} **Handshake Failed.** Link closed.");
    } else if (cleanLine.includes("Discovered Local NetNavis:")) {
      this.onMessage("system", "\u{1F4C2} **Discovered Local NetNavis:**");
    } else if (cleanLine.startsWith("  * ") && (cleanLine.includes("at") || cleanLine.includes("Key:"))) {
      this.onMessage("system", cleanLine);
    } else if (cleanLine.startsWith("[System]") || cleanLine.startsWith("--- STEP") || cleanLine.startsWith("\u2714 Shared Secret")) {
      this.onMessage("system", `\u2699\uFE0F *${cleanLine}*`);
    } else if (cleanLine.includes("Public Identity Pubkey:")) {
      this.onMessage("system", `\u{1F511} *${cleanLine}*`);
    } else if (cleanLine.startsWith("  * ") && cleanLine.includes("Key")) {
      this.onMessage("system", `\u{1F511} *${cleanLine}*`);
    }
  }
  send(text) {
    var _a;
    if (!this.isRunning || !this.process)
      return;
    (_a = this.process.stdin) == null ? void 0 : _a.write(text + "\n");
  }
  stop() {
    if (this.process) {
      this.process.kill();
      this.process = null;
    }
    this.isRunning = false;
  }
};

// src/main.ts
var path3 = __toESM(require("path"));
var NetNaviPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.commsRunning = false;
    this.isStreaming = false;
  }
  async onload() {
    console.log("[NetNavi] Booting system...");
    this.settingsManager = new SettingsManager(this);
    await this.settingsManager.loadSettings();
    this.stateManager = new StateManager("idle");
    this.history = new ConversationHistory();
    this.vaultExecutor = new VaultExecutor(this.app);
    this.vaultSearcher = new VaultSearcher(this.app);
    this.localBridge = new LocalBridge();
    const adapter = this.app.vault.adapter;
    const basePath = adapter.getBasePath ? adapter.getBasePath() : "";
    this.commsBridge = new CommsBridge(
      this.localBridge.pythonPath,
      path3.join(basePath, "netnavi_cli.py")
    );
    this.widget = new AvatarWidget(this, this.settingsManager);
    this.assetLoader = new AssetLoader(this.app, this.settingsManager.current.assetFolderPath);
    this.mediaRenderer = new MediaRenderer(
      this.widget.avatarContainer,
      this.settingsManager.current.transitionFadeDuration
    );
    this.idleEngine = new IdleEngine(
      this.assetLoader,
      this.mediaRenderer,
      this.settingsManager.current.animationTiming
    );
    this.stateManager.onChange(async (newState) => {
      if (newState === "idle") {
        await this.idleEngine.start();
      } else {
        this.idleEngine.stop();
        const assets = await this.assetLoader.getAssetsForState(newState);
        if (assets.length > 0)
          this.mediaRenderer.render(assets[0]);
      }
    });
    await this.idleEngine.start();
    this.cooldownManager = new CooldownManager(this.stateManager);
    this.triggerEvaluator = new TriggerEvaluator(this.settingsManager, this.cooldownManager);
    this.eventBus = new EventBus(this, this.triggerEvaluator);
    this.eventBus.registerObsidianHooks();
    this.aiClient = new AntigravityClient(this.settingsManager);
    this.voiceEngine = new VoiceEngine(this);
    this.responsePanel = new ResponsePanel(this.vaultExecutor, this.app, this.settingsManager);
    this.viewManager = new ViewManager(this);
    this.viewManager.registerViews();
    if (this.settingsManager.current.uiMode === "docked") {
      this.app.workspace.onLayoutReady(async () => {
        await this.viewManager.activateView();
      });
    }
    this.widget.chatInput.addEventListener("keydown", async (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        await this.handleUserMessage(this.widget.chatInput.value.trim());
      }
    });
    let isRecording = false;
    this.widget.micButton.addEventListener("click", async () => {
      if (!isRecording) {
        isRecording = true;
        await this.voiceEngine.startRecording(this.widget.micButton);
      } else {
        isRecording = false;
        const wavBuffer = await this.voiceEngine.stopRecording(this.widget.micButton);
        if (wavBuffer) {
          this.stateManager.setState("thinking");
          try {
            const res = await fetch("http://127.0.0.1:8000/voice/stt", {
              method: "POST",
              headers: { "Content-Type": "audio/wav" },
              body: wavBuffer
            });
            if (res.ok) {
              const data = await res.json();
              if (data.status === "success" && data.text) {
                this.widget.chatInput.value = data.text;
                this.widget.chatInput.focus();
              }
            }
          } catch (e) {
            console.error("[NetNavi] STT upload failed:", e);
          } finally {
            this.stateManager.setState("idle");
          }
        }
      }
    });
    this.statusSync = new StatusSync(this.app, this.stateManager);
    this.statusSync.startPolling();
    this.addSettingTab(new EmotionEditorModal(this.app, this));
    this.addCommand({
      id: "open-netnavi-view",
      name: "Open NetNavi Interface",
      callback: () => {
        this.viewManager.activateView();
      }
    });
    console.log("[NetNavi] System online.");
  }
  /**
   * Central message handler — connects input → AI → avatar → response panel.
   */
  async handleUserMessage(prompt) {
    if (!prompt || this.isStreaming)
      return;
    this.isStreaming = true;
    this.widget.chatInput.value = "";
    this.widget.chatInput.disabled = true;
    this.responsePanel.addUserMessage(prompt);
    this.history.add("user", prompt);
    if (prompt.startsWith("@p2p ")) {
      const commsCommand = prompt.replace("@p2p ", "").trim();
      if (!this.commsRunning) {
        this.commsBridge.start(async (type, text) => {
          this.responsePanel.beginStream();
          await this.responsePanel.appendChunk(text);
          await this.responsePanel.finalizeStream();
        });
        this.commsRunning = true;
      }
      if (commsCommand.startsWith("connect ")) {
        const ipToken = commsCommand.replace("connect ", "").trim();
        this.commsBridge.send(`/connect ${ipToken}`);
      } else if (commsCommand.startsWith("connect-nostr ")) {
        const keyToken = commsCommand.replace("connect-nostr ", "").trim();
        this.commsBridge.send(`/connect-nostr ${keyToken}`);
      } else if (commsCommand === "list") {
        this.commsBridge.send("/list");
      } else if (commsCommand === "status") {
        this.commsBridge.send("/status");
      } else if (commsCommand === "exit") {
        this.commsBridge.send("/exit");
        this.commsBridge.stop();
        this.commsRunning = false;
      } else {
        this.commsBridge.send(`/${commsCommand}`);
      }
      this.isStreaming = false;
      this.widget.chatInput.disabled = false;
      this.widget.chatInput.focus();
      return;
    }
    if (this.commsRunning) {
      this.commsBridge.send(prompt);
      this.isStreaming = false;
      this.widget.chatInput.disabled = false;
      this.widget.chatInput.focus();
      return;
    }
    this.stateManager.setState("thinking");
    this.responsePanel.beginStream();
    let apiPrompt = prompt;
    let isLocalSearch = false;
    if (prompt.startsWith("@remember ")) {
      this.stateManager.setState("taking_notes");
      await this.responsePanel.appendChunk(`\u{1F9E0} *Storing new memory into Pinecone index...*

`);
      let textToStore = prompt.replace("@remember ", "").trim();
      const tags = [];
      const tagRegex = /#(\w+)/g;
      let match;
      while ((match = tagRegex.exec(textToStore)) !== null) {
        tags.push(match[1]);
      }
      const cleanText = textToStore.replace(tagRegex, "").trim();
      const result = await this.localBridge.store(cleanText, tags.join(","));
      if (result.status === "success") {
        await this.responsePanel.appendChunk(
          `\u2705 **Memory Saved!**
\u2022 **ID:** \`${result.id}\`
\u2022 **Content:** "${cleanText}"
` + (tags.length > 0 ? `\u2022 **Tags:** ${tags.map((t) => `\`#${t}\``).join(", ")}
` : "")
        );
      } else {
        await this.responsePanel.appendChunk(`\u274C **Failed to store memory:** ${result.error}
`);
      }
      await this.responsePanel.finalizeStream();
      this.stateManager.setState("idle");
      this.isStreaming = false;
      this.widget.chatInput.disabled = false;
      this.widget.chatInput.focus();
      return;
    }
    if (prompt.startsWith("@brain ")) {
      isLocalSearch = true;
      const query = prompt.replace("@brain ", "").trim();
      this.stateManager.setState("local_search");
      await this.responsePanel.appendChunk(`\u{1F9E0} *Querying Pinecone vector database for: "${query}"...*

`);
      const result = await this.localBridge.query(query, 3);
      if (result.error) {
        await this.responsePanel.appendChunk(`\u26A0\uFE0F **Pinecone Query failed:** ${result.error}
Proceeding with general query...

`);
        apiPrompt = query;
      } else if (result.matches && result.matches.length > 0) {
        let context = "--- CONTEXT FROM PINECONE LONG-TERM MEMORY ---\n";
        let referencesList = "\u{1F4C2} *Semantic matches retrieved:*\n";
        result.matches.forEach((match, index) => {
          var _a, _b;
          const text = match.metadata.text;
          const scorePercent = Math.round(match.score * 100);
          const preview = text.length > 60 ? text.slice(0, 60) + "..." : text;
          context += `[Memory #${index + 1}] (Relevance: ${scorePercent}%)
`;
          context += `${text}
`;
          context += `Tags: ${(_b = (_a = match.metadata.tags) == null ? void 0 : _a.join(", ")) != null ? _b : "None"}

`;
          referencesList += `\u2022 **[${scorePercent}%]** "${preview}"
`;
        });
        context += "----------------------------------------------\n";
        await this.responsePanel.appendChunk(referencesList + "\n");
        apiPrompt = `${context}

User Question: ${query}`;
      } else {
        await this.responsePanel.appendChunk(`\u26A0\uFE0F *No similar memories found in Pinecone. Proceeding with query...*

`);
        apiPrompt = query;
      }
    } else if (prompt.startsWith("@search ")) {
      isLocalSearch = true;
      const query = prompt.replace("@search ", "").trim();
      this.stateManager.setState("local_search");
      await this.responsePanel.appendChunk(`\u{1F50D} *Searching vault for: "${query}"...*

`);
      const results = await this.vaultSearcher.search(query);
      if (results.length > 0) {
        const context = await this.vaultSearcher.formatContext(results);
        const fileList = results.map((r) => `\u2022 [[${r.file.basename}]]`).join("\n");
        await this.responsePanel.appendChunk(`\u{1F4C2} *References parsed from vault:*
${fileList}

`);
        apiPrompt = `${context}

User Query: ${query}`;
      } else {
        await this.responsePanel.appendChunk(`\u26A0\uFE0F *No matching notes found. Proceeding with general query...*

`);
        apiPrompt = query;
      }
    }
    let fullResponse = "";
    try {
      for await (const chunk of this.aiClient.stream(apiPrompt, this.history)) {
        fullResponse += chunk;
        await this.responsePanel.appendChunk(chunk);
        if (!isLocalSearch) {
          const detectedState = ActionParser.parse(chunk);
          if (detectedState && detectedState !== "idle") {
            this.stateManager.setState(detectedState);
          }
        }
      }
    } finally {
      await this.responsePanel.finalizeStream();
      this.history.add("assistant", fullResponse);
      const cleanText = fullResponse.replace(/<thought>[\s\S]*?<\/thought>/g, "").replace(/[#*`_\[\]()\-]/g, "").replace(/\n+/g, " ").trim();
      if (cleanText) {
        this.voiceEngine.speak(cleanText);
      }
      this.stateManager.setState("idle");
      this.isStreaming = false;
      this.widget.chatInput.disabled = false;
      this.widget.chatInput.focus();
    }
  }
  onunload() {
    var _a, _b, _c, _d, _e, _f, _g;
    console.log("[NetNavi] Shutting down...");
    (_a = this.commsBridge) == null ? void 0 : _a.stop();
    (_b = this.viewManager) == null ? void 0 : _b.deactivateView();
    (_c = this.statusSync) == null ? void 0 : _c.stopPolling();
    (_d = this.idleEngine) == null ? void 0 : _d.stop();
    (_e = this.mediaRenderer) == null ? void 0 : _e.clear();
    (_f = this.widget) == null ? void 0 : _f.destroy();
    (_g = this.responsePanel) == null ? void 0 : _g.destroy();
  }
};
