#!/usr/bin/env python3
import argparse
import os
import sys
import json
import subprocess
from datetime import datetime

VAULT_PATH = "/media/davidr/Obsidianman"
BRIDGE_SCRIPT = f"{VAULT_PATH}/usr/scripts/gemini_bridge.py"
COORD_LOG = f"{VAULT_PATH}/.claudian/coordination.log"
AUDIT_LOG = f"{VAULT_PATH}/003_Resources/+/gemini_audit_log.md"

def log_coordination(task, status, output_hash):
    os.makedirs(os.path.dirname(COORD_LOG), exist_ok=True)
    entry = {
        "timestamp": datetime.now().isoformat(),
        "event": "multi_agent_handoff",
        "task": task,
        "status": status,
        "output_hash": output_hash
    }
    
    with open(COORD_LOG, "a") as f:
        f.write(json.dumps(entry) + "\n")
        
    md_entry = f"**{entry['timestamp']}** [MULTI-AGENT HANDOFF]\n```json\n{json.dumps(entry, indent=2)}\n```\n---\n"
    with open(AUDIT_LOG, "a") as f:
        f.write(md_entry)

def execute_handoff(spec_file):
    if not os.path.exists(spec_file):
        print(f"❌ Spec file not found: {spec_file}")
        sys.exit(1)
        
    with open(spec_file, "r") as f:
        try:
            spec = json.load(f)
        except json.JSONDecodeError:
            print("❌ Invalid JSON handoff spec.")
            sys.exit(1)
            
    task_name = spec.get("task", "unnamed_handoff")
    prompt = spec.get("prompt", "")
    layer = spec.get("layer", "PRIVATE") # Safety default
    
    print(f"🤝 Executing Handoff: {task_name} (Layer: {layer})")
    
    # Constructing the Gemini CLI query from the spec
    gemini_cmd = f"gemini --prompt '{prompt}' > /tmp/{task_name}_result.md"
    
    cmd = [
        BRIDGE_SCRIPT,
        "--task", task_name,
        "--layer", layer,
        "--prompt", gemini_cmd
    ]
    
    try:
        subprocess.run(cmd, check=True)
        # Log successful transfer back to Antigravity
        log_coordination(task_name, "success", "bridge_executed")
        print("✅ Handoff executed. Result available in /tmp/ for Antigravity synthesis.")
    except subprocess.CalledProcessError:
        log_coordination(task_name, "failed", "null")
        print("❌ Handoff failed or was aborted at the bridge layer.")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Multi-Agent Handoff Protocol")
    parser.add_argument("--spec", required=True, help="JSON spec file generated by Antigravity")
    args = parser.parse_args()
    
    execute_handoff(args.spec)

if __name__ == "__main__":
    main()
